---

- name: Add Brave repository public key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    state: present
  become: yes

- name: Add Brave repository
  apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
  become: yes

- name: Install Brave
  apt:
    name: brave-browser
    state: present
  become: yes